import type { MascotMood } from '../mascot/Mascot';

export type UnitIntroDef = {
  unitId: string;
  grade: number;
  title: string;
  subtitle: string;
  concept: string;
  mascotMood: MascotMood;
  accentColor: string;
};

export const GRADE_1_INTROS: Record<string, UnitIntroDef> = {
  'g1-u1': {
    unitId: 'g1-u1',
    grade: 1,
    title: 'Unit 1 · Numbers to 10',
    subtitle: 'Counting & Subitizing',
    concept: 'Tap and count things one by one up to ten!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g1-u2': {
    unitId: 'g1-u2',
    grade: 1,
    title: 'Unit 2 · Add & Subtract',
    subtitle: 'Putting Together & Taking Away',
    concept: 'Join two groups together to make more, or take some away!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g1-u3': {
    unitId: 'g1-u3',
    grade: 1,
    title: 'Unit 3 · Numbers to 20',
    subtitle: 'Teen Numbers',
    concept: 'One full ten plus extra ones make teen numbers!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g1-u4': {
    unitId: 'g1-u4',
    grade: 1,
    title: 'Unit 4 · Add & Subtract to 20',
    subtitle: 'Bridging Through 10',
    concept: 'Make a ten first, then jump the rest of the way!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g1-u5': {
    unitId: 'g1-u5',
    grade: 1,
    title: 'Unit 5 · Numbers to 100',
    subtitle: 'Tens & Big Numbers',
    concept: 'Group tens together to count all the way to one hundred!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g1-u6': {
    unitId: 'g1-u6',
    grade: 1,
    title: 'Unit 6 · Shapes',
    subtitle: 'Flat & Solid Shapes',
    concept: 'Look at sides and corners to spot triangles, squares, and circles!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g1-u7': {
    unitId: 'g1-u7',
    grade: 1,
    title: 'Unit 7 · Measure & Time',
    subtitle: 'Clocks, Length & Money',
    concept: 'Tick-tock on the clock, compare lengths, and count coins!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
  'g1-u8': {
    unitId: 'g1-u8',
    grade: 1,
    title: 'Unit 8 · Patterns & Data',
    subtitle: 'Repeating Patterns & Charts',
    concept: 'Spot what repeats next and count tally marks in graphs!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-8)',
  },
};

export const GRADE_2_INTROS: Record<string, UnitIntroDef> = {
  'g2-u1': {
    unitId: 'g2-u1',
    grade: 2,
    title: 'Unit 1 · Numbers to 1000',
    subtitle: 'Hundreds, Tens & Ones',
    concept: 'Ten hundreds make a thousand! Read and round 3-digit numbers.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g2-u2': {
    unitId: 'g2-u2',
    grade: 2,
    title: 'Unit 2 · Add & Subtract',
    subtitle: 'Written Column Methods & Regrouping',
    concept: 'Add ones first, then add tens! Open a ten when you need more ones.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g2-u3': {
    unitId: 'g2-u3',
    grade: 2,
    title: 'Unit 3 · Mental Math',
    subtitle: 'Quick Tricks & Near Tens',
    concept: 'Jump 10 or 100 fast in your head, and double numbers in a flash!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g2-u4': {
    unitId: 'g2-u4',
    grade: 2,
    title: 'Unit 4 · Meet Multiplication',
    subtitle: 'Equal Groups & Times Tables',
    concept: 'Rows and groups of the same size! Master ×2, ×5, and ×10.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-4)',
  },
  'g2-u5': {
    unitId: 'g2-u5',
    grade: 2,
    title: 'Unit 5 · Even, Odd & Patterns',
    subtitle: 'Pairs & Growing Patterns',
    concept: 'Fair pairs are even! Spot growing steps on the hundreds chart.',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g2-u6': {
    unitId: 'g2-u6',
    grade: 2,
    title: 'Unit 6 · Measure',
    subtitle: 'Centimetres, Metres, Grams & Kilos',
    concept: 'Line up from zero with your ruler, and weigh items in grams and kg!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g2-u7': {
    unitId: 'g2-u7',
    grade: 2,
    title: 'Unit 7 · Time, Money & Data',
    subtitle: 'Quarter Hours, Rupiah & Bar Charts',
    concept: 'Read quarter past and quarter to, give change, and read bar graphs!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_3_INTROS: Record<string, UnitIntroDef> = {
  'g3-u1': {
    unitId: 'g3-u1',
    grade: 3,
    title: 'Unit 1 · Numbers to 10.000',
    subtitle: 'Thousands & Rounding',
    concept: 'Ten thousands line up on the big number line! Round to nearest hundred.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g3-u2': {
    unitId: 'g3-u2',
    grade: 3,
    title: 'Unit 2 · Times Tables',
    subtitle: '×3, ×4, ×6, ×7, ×8, ×9',
    concept: 'Turn-around facts make multiplication twice as easy! 6 × 7 = 7 × 6.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g3-u3': {
    unitId: 'g3-u3',
    grade: 3,
    title: 'Unit 3 · Division',
    subtitle: 'Sharing & Equal Groups',
    concept: 'Share equally into piles or count how many fit! Spot the leftovers.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g3-u4': {
    unitId: 'g3-u4',
    grade: 3,
    title: 'Unit 4 · Add & Subtract to 1000',
    subtitle: '3-Digit Regrouping',
    concept: 'Three columns! Add ones, tens, then hundreds with carrying.',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g3-u5': {
    unitId: 'g3-u5',
    grade: 3,
    title: 'Unit 5 · Fractions',
    subtitle: 'Halves, Thirds, Fourths & Beyond',
    concept: 'Equal slices of the whole! Find fractions on the number line.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g3-u6': {
    unitId: 'g3-u6',
    grade: 3,
    title: 'Unit 6 · Shapes & Perimeter',
    subtitle: 'Square Corners & Walking Around',
    concept: 'Measure all sides and add them up to find the perimeter around the fence!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g3-u7': {
    unitId: 'g3-u7',
    grade: 3,
    title: 'Unit 7 · Time, Money & Data',
    subtitle: 'To the Minute, Shopping & Bar Graphs',
    concept: 'Tell time to the exact minute and count money up to Rp 100.000!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_4_INTROS: Record<string, UnitIntroDef> = {
  'g4-u1': {
    unitId: 'g4-u1',
    grade: 4,
    title: 'Unit 1 · Big Numbers',
    subtitle: 'Numbers to 1.000.000',
    concept: 'Ten thousands and hundred thousands line up to one million!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g4-u2': {
    unitId: 'g4-u2',
    grade: 4,
    title: 'Unit 2 · Multiply & Divide Bigger',
    subtitle: 'Split to Multiply & Long Division',
    concept: 'Split big numbers to multiply easily, and divide with remainders!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g4-u3': {
    unitId: 'g4-u3',
    grade: 4,
    title: 'Unit 3 · Factors & Multiples',
    subtitle: 'Primes & Common Multiples',
    concept: 'Find factor pairs that multiply together, and spot prime numbers!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g4-u4': {
    unitId: 'g4-u4',
    grade: 4,
    title: 'Unit 4 · Equivalent Fractions',
    subtitle: 'Same Size, Mixed Numbers',
    concept: 'Multiply top and bottom by the same number to keep equal slices!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-4)',
  },
  'g4-u5': {
    unitId: 'g4-u5',
    grade: 4,
    title: 'Unit 5 · Decimals Begin',
    subtitle: 'Tenths & Hundredths',
    concept: 'Tenths and hundredths are fractions written with a decimal point!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g4-u6': {
    unitId: 'g4-u6',
    grade: 4,
    title: 'Unit 6 · Angles & Area',
    subtitle: 'Degrees & Square Units',
    concept: 'Turn full circle 360° and count square units to find total area!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g4-u7': {
    unitId: 'g4-u7',
    grade: 4,
    title: 'Unit 7 · Data',
    subtitle: 'Line Plots & Multi-bar Graphs',
    concept: 'Plot marks on a line and compare bars side by side!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_5_INTROS: Record<string, UnitIntroDef> = {
  'g5-u1': {
    unitId: 'g5-u1',
    grade: 5,
    title: 'Unit 1 · Fraction Operations',
    subtitle: 'Unlike Bottoms & Fraction Multiply',
    concept: 'Match denominators first before adding, and multiply tops and bottoms!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-1)',
  },
  'g5-u2': {
    unitId: 'g5-u2',
    grade: 5,
    title: 'Unit 2 · Decimals',
    subtitle: 'Thousandths & Decimal Arithmetic',
    concept: 'Line up decimal points straight down when adding and subtracting!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-2)',
  },
  'g5-u3': {
    unitId: 'g5-u3',
    grade: 5,
    title: 'Unit 3 · Percent',
    subtitle: 'Parts of 100 & Discounts',
    concept: 'Percent means out of 100! 50% is half and 25% is a quarter.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g5-u4': {
    unitId: 'g5-u4',
    grade: 5,
    title: 'Unit 4 · Multiply & Divide Fluently',
    subtitle: '2-Digit × 2-Digit & Squares',
    concept: 'Area model and standard columns make big multiplication easy!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g5-u5': {
    unitId: 'g5-u5',
    grade: 5,
    title: 'Unit 5 · Volume & Measurement',
    subtitle: 'Cubic Units & Box Capacity',
    concept: 'Length × width × height counts how many cubic blocks fill the box!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g5-u6': {
    unitId: 'g5-u6',
    grade: 5,
    title: 'Unit 6 · Shapes in Space',
    subtitle: '3D Solids & Unfolding Nets',
    concept: 'Unfold cubes and pyramids into flat paper nets with matching faces!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g5-u7': {
    unitId: 'g5-u7',
    grade: 5,
    title: 'Unit 7 · Data & Speed',
    subtitle: 'Distance, Speed & Mean Average',
    concept: 'Speed tells how far each hour, and mean balances all values equally!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_6_INTROS: Record<string, UnitIntroDef> = {
  'g6-u1': {
    unitId: 'g6-u1',
    grade: 6,
    title: 'Unit 1 · Integers',
    subtitle: 'Below Zero & Integer Math',
    concept: 'Negative numbers live left of zero! Minus a minus jumps right.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-1)',
  },
  'g6-u2': {
    unitId: 'g6-u2',
    grade: 6,
    title: 'Unit 2 · Ratio & Proportion',
    subtitle: 'Comparing Parts & Scaling',
    concept: 'Ratios scale up and down like recipes: 2 to 3 is 4 to 6!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g6-u3': {
    unitId: 'g6-u3',
    grade: 6,
    title: 'Unit 3 · Algebra Begins',
    subtitle: 'Mystery Letter n & Equations',
    concept: 'n is just a number in disguise! Undo operations to find n.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-3)',
  },
  'g6-u4': {
    unitId: 'g6-u4',
    grade: 6,
    title: 'Unit 4 · Circles',
    subtitle: 'Radius, Diameter & Circumference',
    concept: 'Diameter is double the radius, and perimeter around is π × d!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-4)',
  },
  'g6-u5': {
    unitId: 'g6-u5',
    grade: 6,
    title: 'Unit 5 · Solids',
    subtitle: 'Prisms, Cylinders & Surface Area',
    concept: 'Base area times height gives prism volume, plus surface area around!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g6-u6': {
    unitId: 'g6-u6',
    grade: 6,
    title: 'Unit 6 · Coordinates',
    subtitle: '4 Quadrants & Graphing Points',
    concept: 'Crawl across x first, then fly up y! Four quadrants meet at (0,0).',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-6)',
  },
  'g6-u7': {
    unitId: 'g6-u7',
    grade: 6,
    title: 'Unit 7 · Statistics & Chance',
    subtitle: 'Median, Range & Probability',
    concept: 'Find the middle number, measure spread, and calculate real chance!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const ALL_UNIT_INTROS: Record<string, UnitIntroDef> = {
  ...GRADE_1_INTROS,
  ...GRADE_2_INTROS,
  ...GRADE_3_INTROS,
  ...GRADE_4_INTROS,
  ...GRADE_5_INTROS,
  ...GRADE_6_INTROS,
};

export function getUnitIntro(unitId: string): UnitIntroDef | null {
  return ALL_UNIT_INTROS[unitId] ?? null;
}
