import type { MascotMood } from '../mascot/Mascot';

export type UnitIntroDef = {
  unitId: string;
  grade: number;
  title: string;
  subtitle: string;
  concept: string;
  mascotMood: MascotMood;
  accentColor: string;
};

export const GRADE_1_INTROS: Record<string, UnitIntroDef> = {
  'g1-u1': {
    unitId: 'g1-u1',
    grade: 1,
    title: 'Unit 1 · Numbers to 10',
    subtitle: 'Counting & Subitizing',
    concept: 'Tap and count things one by one up to ten!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g1-u2': {
    unitId: 'g1-u2',
    grade: 1,
    title: 'Unit 2 · Add & Subtract',
    subtitle: 'Putting Together & Taking Away',
    concept: 'Join two groups together to make more, or take some away!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g1-u3': {
    unitId: 'g1-u3',
    grade: 1,
    title: 'Unit 3 · Numbers to 20',
    subtitle: 'Teen Numbers',
    concept: 'One full ten plus extra ones make teen numbers!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g1-u4': {
    unitId: 'g1-u4',
    grade: 1,
    title: 'Unit 4 · Add & Subtract to 20',
    subtitle: 'Bridging Through 10',
    concept: 'Make a ten first, then jump the rest of the way!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g1-u5': {
    unitId: 'g1-u5',
    grade: 1,
    title: 'Unit 5 · Numbers to 100',
    subtitle: 'Tens & Big Numbers',
    concept: 'Group tens together to count all the way to one hundred!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g1-u6': {
    unitId: 'g1-u6',
    grade: 1,
    title: 'Unit 6 · Shapes',
    subtitle: 'Flat & Solid Shapes',
    concept: 'Look at sides and corners to spot triangles, squares, and circles!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g1-u7': {
    unitId: 'g1-u7',
    grade: 1,
    title: 'Unit 7 · Measure & Time',
    subtitle: 'Clocks, Length & Money',
    concept: 'Tick-tock on the clock, compare lengths, and count coins!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
  'g1-u8': {
    unitId: 'g1-u8',
    grade: 1,
    title: 'Unit 8 · Patterns & Data',
    subtitle: 'Repeating Patterns & Charts',
    concept: 'Spot what repeats next and count tally marks in graphs!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-8)',
  },
};

export const GRADE_2_INTROS: Record<string, UnitIntroDef> = {
  'g2-u1': {
    unitId: 'g2-u1',
    grade: 2,
    title: 'Unit 1 · Numbers to 1000',
    subtitle: 'Hundreds, Tens & Ones',
    concept: 'Ten hundreds make a thousand! Read and round 3-digit numbers.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g2-u2': {
    unitId: 'g2-u2',
    grade: 2,
    title: 'Unit 2 · Add & Subtract',
    subtitle: 'Written Column Methods & Regrouping',
    concept: 'Add ones first, then add tens! Open a ten when you need more ones.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g2-u3': {
    unitId: 'g2-u3',
    grade: 2,
    title: 'Unit 3 · Mental Math',
    subtitle: 'Quick Tricks & Near Tens',
    concept: 'Jump 10 or 100 fast in your head, and double numbers in a flash!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g2-u4': {
    unitId: 'g2-u4',
    grade: 2,
    title: 'Unit 4 · Meet Multiplication',
    subtitle: 'Equal Groups & Times Tables',
    concept: 'Rows and groups of the same size! Master ×2, ×5, and ×10.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-4)',
  },
  'g2-u5': {
    unitId: 'g2-u5',
    grade: 2,
    title: 'Unit 5 · Even, Odd & Patterns',
    subtitle: 'Pairs & Growing Patterns',
    concept: 'Fair pairs are even! Spot growing steps on the hundreds chart.',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g2-u6': {
    unitId: 'g2-u6',
    grade: 2,
    title: 'Unit 6 · Measure',
    subtitle: 'Centimetres, Metres, Grams & Kilos',
    concept: 'Line up from zero with your ruler, and weigh items in grams and kg!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g2-u7': {
    unitId: 'g2-u7',
    grade: 2,
    title: 'Unit 7 · Time, Money & Data',
    subtitle: 'Quarter Hours, Rupiah & Bar Charts',
    concept: 'Read quarter past and quarter to, give change, and read bar graphs!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_3_INTROS: Record<string, UnitIntroDef> = {
  'g3-u1': {
    unitId: 'g3-u1',
    grade: 3,
    title: 'Unit 1 · Numbers to 10.000',
    subtitle: 'Thousands & Rounding',
    concept: 'Ten thousands line up on the big number line! Round to nearest hundred.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g3-u2': {
    unitId: 'g3-u2',
    grade: 3,
    title: 'Unit 2 · Times Tables',
    subtitle: '×3, ×4, ×6, ×7, ×8, ×9',
    concept: 'Turn-around facts make multiplication twice as easy! 6 × 7 = 7 × 6.',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g3-u3': {
    unitId: 'g3-u3',
    grade: 3,
    title: 'Unit 3 · Division',
    subtitle: 'Sharing & Equal Groups',
    concept: 'Share equally into piles or count how many fit! Spot the leftovers.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g3-u4': {
    unitId: 'g3-u4',
    grade: 3,
    title: 'Unit 4 · Add & Subtract to 1000',
    subtitle: '3-Digit Regrouping',
    concept: 'Three columns! Add ones, tens, then hundreds with carrying.',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g3-u5': {
    unitId: 'g3-u5',
    grade: 3,
    title: 'Unit 5 · Fractions',
    subtitle: 'Halves, Thirds, Fourths & Beyond',
    concept: 'Equal slices of the whole! Find fractions on the number line.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g3-u6': {
    unitId: 'g3-u6',
    grade: 3,
    title: 'Unit 6 · Shapes & Perimeter',
    subtitle: 'Square Corners & Walking Around',
    concept: 'Measure all sides and add them up to find the perimeter around the fence!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g3-u7': {
    unitId: 'g3-u7',
    grade: 3,
    title: 'Unit 7 · Time, Money & Data',
    subtitle: 'To the Minute, Shopping & Bar Graphs',
    concept: 'Tell time to the exact minute and count money up to Rp 100.000!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_4_INTROS: Record<string, UnitIntroDef> = {
  'g4-u1': {
    unitId: 'g4-u1',
    grade: 4,
    title: 'Unit 1 · Big Numbers',
    subtitle: 'Numbers to 1.000.000',
    concept: 'Ten thousands and hundred thousands line up to one million!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-1)',
  },
  'g4-u2': {
    unitId: 'g4-u2',
    grade: 4,
    title: 'Unit 2 · Multiply & Divide Bigger',
    subtitle: 'Split to Multiply & Long Division',
    concept: 'Split big numbers to multiply easily, and divide with remainders!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g4-u3': {
    unitId: 'g4-u3',
    grade: 4,
    title: 'Unit 3 · Factors & Multiples',
    subtitle: 'Primes & Common Multiples',
    concept: 'Find factor pairs that multiply together, and spot prime numbers!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g4-u4': {
    unitId: 'g4-u4',
    grade: 4,
    title: 'Unit 4 · Equivalent Fractions',
    subtitle: 'Same Size, Mixed Numbers',
    concept: 'Multiply top and bottom by the same number to keep equal slices!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-4)',
  },
  'g4-u5': {
    unitId: 'g4-u5',
    grade: 4,
    title: 'Unit 5 · Decimals Begin',
    subtitle: 'Tenths & Hundredths',
    concept: 'Tenths and hundredths are fractions written with a decimal point!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g4-u6': {
    unitId: 'g4-u6',
    grade: 4,
    title: 'Unit 6 · Angles & Area',
    subtitle: 'Degrees & Square Units',
    concept: 'Turn full circle 360° and count square units to find total area!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g4-u7': {
    unitId: 'g4-u7',
    grade: 4,
    title: 'Unit 7 · Data',
    subtitle: 'Line Plots & Multi-bar Graphs',
    concept: 'Plot marks on a line and compare bars side by side!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_5_INTROS: Record<string, UnitIntroDef> = {
  'g5-u1': {
    unitId: 'g5-u1',
    grade: 5,
    title: 'Unit 1 · Fraction Operations',
    subtitle: 'Unlike Bottoms & Fraction Multiply',
    concept: 'Match denominators first before adding, and multiply tops and bottoms!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-1)',
  },
  'g5-u2': {
    unitId: 'g5-u2',
    grade: 5,
    title: 'Unit 2 · Decimals',
    subtitle: 'Thousandths & Decimal Arithmetic',
    concept: 'Line up decimal points straight down when adding and subtracting!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-2)',
  },
  'g5-u3': {
    unitId: 'g5-u3',
    grade: 5,
    title: 'Unit 3 · Percent',
    subtitle: 'Parts of 100 & Discounts',
    concept: 'Percent means out of 100! 50% is half and 25% is a quarter.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-3)',
  },
  'g5-u4': {
    unitId: 'g5-u4',
    grade: 5,
    title: 'Unit 4 · Multiply & Divide Fluently',
    subtitle: '2-Digit × 2-Digit & Squares',
    concept: 'Area model and standard columns make big multiplication easy!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-4)',
  },
  'g5-u5': {
    unitId: 'g5-u5',
    grade: 5,
    title: 'Unit 5 · Volume & Measurement',
    subtitle: 'Cubic Units & Box Capacity',
    concept: 'Length × width × height counts how many cubic blocks fill the box!',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-5)',
  },
  'g5-u6': {
    unitId: 'g5-u6',
    grade: 5,
    title: 'Unit 6 · Shapes in Space',
    subtitle: '3D Solids & Unfolding Nets',
    concept: 'Unfold cubes and pyramids into flat paper nets with matching faces!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-6)',
  },
  'g5-u7': {
    unitId: 'g5-u7',
    grade: 5,
    title: 'Unit 7 · Data & Speed',
    subtitle: 'Distance, Speed & Mean Average',
    concept: 'Speed tells how far each hour, and mean balances all values equally!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const GRADE_6_INTROS: Record<string, UnitIntroDef> = {
  'g6-u1': {
    unitId: 'g6-u1',
    grade: 6,
    title: 'Unit 1 · Integers',
    subtitle: 'Below Zero & Integer Math',
    concept: 'Negative numbers live left of zero! Minus a minus jumps right.',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-1)',
  },
  'g6-u2': {
    unitId: 'g6-u2',
    grade: 6,
    title: 'Unit 2 · Ratio & Proportion',
    subtitle: 'Comparing Parts & Scaling',
    concept: 'Ratios scale up and down like recipes: 2 to 3 is 4 to 6!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-2)',
  },
  'g6-u3': {
    unitId: 'g6-u3',
    grade: 6,
    title: 'Unit 3 · Algebra Begins',
    subtitle: 'Mystery Letter n & Equations',
    concept: 'n is just a number in disguise! Undo operations to find n.',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-3)',
  },
  'g6-u4': {
    unitId: 'g6-u4',
    grade: 6,
    title: 'Unit 4 · Circles',
    subtitle: 'Radius, Diameter & Circumference',
    concept: 'Diameter is double the radius, and perimeter around is π × d!',
    mascotMood: 'thinking',
    accentColor: 'var(--c-unit-4)',
  },
  'g6-u5': {
    unitId: 'g6-u5',
    grade: 6,
    title: 'Unit 5 · Solids',
    subtitle: 'Prisms, Cylinders & Surface Area',
    concept: 'Base area times height gives prism volume, plus surface area around!',
    mascotMood: 'encourage',
    accentColor: 'var(--c-unit-5)',
  },
  'g6-u6': {
    unitId: 'g6-u6',
    grade: 6,
    title: 'Unit 6 · Coordinates',
    subtitle: '4 Quadrants & Graphing Points',
    concept: 'Crawl across x first, then fly up y! Four quadrants meet at (0,0).',
    mascotMood: 'happy',
    accentColor: 'var(--c-unit-6)',
  },
  'g6-u7': {
    unitId: 'g6-u7',
    grade: 6,
    title: 'Unit 7 · Statistics & Chance',
    subtitle: 'Median, Range & Probability',
    concept: 'Find the middle number, measure spread, and calculate real chance!',
    mascotMood: 'celebrate',
    accentColor: 'var(--c-unit-7)',
  },
};

export const READ_INTROS: Record<string, UnitIntroDef> = {
  'r1-u1': {
    unitId: 'r1-u1',
    grade: 1,
    title: 'Unit 1 · Who, Where & What',
    subtitle: 'Characters & Settings',
    concept: 'Spot who is in the story and where the adventure happens!',
    mascotMood: 'happy',
    accentColor: '#10b981',
  },
  'r1-u2': {
    unitId: 'r1-u2',
    grade: 1,
    title: 'Unit 2 · Beginning, Middle & End',
    subtitle: 'Order of Events',
    concept: 'Follow what happens first, what happens next, and what happens last!',
    mascotMood: 'thinking',
    accentColor: '#059669',
  },
  'r1-u3': {
    unitId: 'r1-u3',
    grade: 1,
    title: 'Unit 3 · Why Did It Happen?',
    subtitle: 'Cause & Effect',
    concept: 'Find the reason why things happen in the story!',
    mascotMood: 'encourage',
    accentColor: '#0d9488',
  },
  'r1-u4': {
    unitId: 'r1-u4',
    grade: 1,
    title: 'Unit 4 · Mystery Clues',
    subtitle: 'Inferring & Riddles',
    concept: 'Read between the lines and use smart clues to solve the riddle!',
    mascotMood: 'celebrate',
    accentColor: '#0284c7',
  },
  'r2-u1': {
    unitId: 'r2-u1',
    grade: 2,
    title: 'Unit 1 · The Big Idea',
    subtitle: 'Main Idea & Details',
    concept: 'Find the one big main idea and see how details support it!',
    mascotMood: 'happy',
    accentColor: '#10b981',
  },
  'r2-u2': {
    unitId: 'r2-u2',
    grade: 2,
    title: 'Unit 2 · Fact or Feeling?',
    subtitle: 'Fact vs Opinion',
    concept: 'Facts can be proven true; opinions tell how someone feels!',
    mascotMood: 'thinking',
    accentColor: '#059669',
  },
  'r2-u3': {
    unitId: 'r2-u3',
    grade: 2,
    title: 'Unit 3 · Character Feelings',
    subtitle: 'Show, Don’t Tell',
    concept: 'Look at actions and body language to tell how characters feel!',
    mascotMood: 'celebrate',
    accentColor: '#0d9488',
  },
  'r2-u4': {
    unitId: 'r2-u4',
    grade: 2,
    title: 'Unit 4 · Which Detail Fits',
    subtitle: 'Supporting Details',
    concept: 'A detail sticks to the big idea. A sentence that wanders does not!',
    mascotMood: 'thinking',
    accentColor: '#0284c7',
  },
  'r3-u1': {
    unitId: 'r3-u1',
    grade: 3,
    title: 'Unit 1 · Follow the Steps',
    subtitle: 'Procedural & Recipes',
    concept: 'Follow steps in exact order to build things and stay safe!',
    mascotMood: 'encourage',
    accentColor: '#10b981',
  },
  'r3-u2': {
    unitId: 'r3-u2',
    grade: 3,
    title: 'Unit 2 · Animal Adaptations',
    subtitle: 'Science & Informational Text',
    concept: 'Discover how special features help animals survive in the wild!',
    mascotMood: 'thinking',
    accentColor: '#0284c7',
  },
  'r3-u3': {
    unitId: 'r3-u3',
    grade: 3,
    title: 'Unit 3 · Problem and Solution',
    subtitle: 'What Went Wrong, What Fixed It',
    concept: 'Spot the problem, then find the sentence that fixes it!',
    mascotMood: 'encourage',
    accentColor: '#0d9488',
  },
  'r3-u4': {
    unitId: 'r3-u4',
    grade: 3,
    title: 'Unit 4 · What Happens First',
    subtitle: 'Order in Information',
    concept: 'Work out which step must happen before the others!',
    mascotMood: 'thinking',
    accentColor: '#059669',
  },
  'r4-u1': {
    unitId: 'r4-u1',
    grade: 4,
    title: 'Unit 1 · Same and Different',
    subtitle: 'Compare Two Short Texts',
    concept: 'Read both texts and see what they share and where they split!',
    mascotMood: 'happy',
    accentColor: '#10b981',
  },
  'r4-u2': {
    unitId: 'r4-u2',
    grade: 4,
    title: 'Unit 2 · Why It Was Written',
    subtitle: 'Author’s Purpose',
    concept: 'Decide if the author wants to teach, amuse, or ask you to act!',
    mascotMood: 'thinking',
    accentColor: '#059669',
  },
  'r4-u3': {
    unitId: 'r4-u3',
    grade: 4,
    title: 'Unit 3 · Words from Context',
    subtitle: 'Meaning from Nearby Clues',
    concept: 'Use the words around a new word to figure out what it means!',
    mascotMood: 'encourage',
    accentColor: '#0d9488',
  },
  'r4-u4': {
    unitId: 'r4-u4',
    grade: 4,
    title: 'Unit 4 · The Lesson',
    subtitle: 'Theme',
    concept: 'The lesson is bigger than one event. What does the story teach?',
    mascotMood: 'celebrate',
    accentColor: '#0284c7',
  },
};

export const SCIENCE_INTROS: Record<string, UnitIntroDef> = {
  's1-u1': {
    unitId: 's1-u1',
    grade: 1,
    title: 'Unit 1 · Living Things',
    subtitle: 'Water, food, and air',
    concept: 'Living things need water, food, and air to stay alive!',
    mascotMood: 'happy',
    accentColor: '#0284c7',
  },
  's1-u2': {
    unitId: 's1-u2',
    grade: 1,
    title: 'Unit 2 · Body and Senses',
    subtitle: 'See, hear, smell, taste, feel',
    concept: 'Eyes see, ears hear, and skin feels hot or cold!',
    mascotMood: 'thinking',
    accentColor: '#0369a1',
  },
  's1-u3': {
    unitId: 's1-u3',
    grade: 1,
    title: 'Unit 3 · Materials',
    subtitle: 'Hard, soft, and change',
    concept: 'Some things sink, some float, and ice melts in the sun!',
    mascotMood: 'encourage',
    accentColor: '#0ea5e9',
  },
  's1-u4': {
    unitId: 's1-u4',
    grade: 1,
    title: 'Unit 4 · Weather',
    subtitle: 'Sun, rain, and wind',
    concept: 'Look at the sky. The sun warms, rain falls, and wind pushes!',
    mascotMood: 'celebrate',
    accentColor: '#38bdf8',
  },
  's1-u5': {
    unitId: 's1-u5',
    grade: 1,
    title: 'Unit 5 · Plant Parts',
    subtitle: 'Root, stem, leaf, flower',
    concept: 'Roots drink, the stem holds up, and a flower grows on top!',
    mascotMood: 'happy',
    accentColor: '#075985',
  },
  's1-u6': {
    unitId: 's1-u6',
    grade: 1,
    title: 'Unit 6 · How Animals Move',
    subtitle: 'Fly, swim, hop, crawl',
    concept: 'Birds fly, fish swim, frogs hop, and worms crawl!',
    mascotMood: 'thinking',
    accentColor: '#0c4a6e',
  },
  's1-u7': {
    unitId: 's1-u7',
    grade: 1,
    title: 'Unit 7 · Day and Night',
    subtitle: 'Sun up, moon up',
    concept: 'The sun makes the day bright. Night is dark and cool!',
    mascotMood: 'encourage',
    accentColor: '#0e7490',
  },
  's1-u8': {
    unitId: 's1-u8',
    grade: 1,
    title: 'Unit 8 · Push and Pull',
    subtitle: 'Away or toward you',
    concept: 'A push sends a thing away. A pull brings it closer to you!',
    mascotMood: 'celebrate',
    accentColor: '#0891b2',
  },
  's1-u9': {
    unitId: 's1-u9',
    grade: 1,
    title: 'Unit 9 · Loud and Quiet',
    subtitle: 'Big sound, soft sound',
    concept: 'A drum is loud. A whisper is quiet. Listen for the sound!',
    mascotMood: 'happy',
    accentColor: '#155e75',
  },
  's1-u10': {
    unitId: 's1-u10',
    grade: 1,
    title: 'Unit 10 · Look After Them',
    subtitle: 'Water, food, gentle hands',
    concept: 'Living things need care. Give water, give food, and use gentle hands!',
    mascotMood: 'thinking',
    accentColor: '#1e3a8a',
  },
  's2-u1': {
    unitId: 's2-u1',
    grade: 2,
    title: 'Unit 1 · Seeds Grow',
    subtitle: 'Water and sun',
    concept: 'A seed needs water and sun before a sprout can grow!',
    mascotMood: 'happy',
    accentColor: '#0f766e',
  },
  's2-u2': {
    unitId: 's2-u2',
    grade: 2,
    title: 'Unit 2 · Animal Homes',
    subtitle: 'A place that fits',
    concept: 'A fish lives in water. A bird lives in a nest!',
    mascotMood: 'thinking',
    accentColor: '#115e59',
  },
  's2-u3': {
    unitId: 's2-u3',
    grade: 2,
    title: 'Unit 3 · Life Cycles',
    subtitle: 'Change in order',
    concept: 'An egg becomes a caterpillar, and a caterpillar becomes a butterfly!',
    mascotMood: 'encourage',
    accentColor: '#047857',
  },
  's2-u4': {
    unitId: 's2-u4',
    grade: 2,
    title: 'Unit 4 · Solid and Liquid',
    subtitle: 'Shape that stays or pours',
    concept: 'A solid keeps its shape. A liquid takes the shape of the cup!',
    mascotMood: 'celebrate',
    accentColor: '#065f46',
  },
  's2-u5': {
    unitId: 's2-u5',
    grade: 2,
    title: 'Unit 5 · Heat and Cold',
    subtitle: 'Melt and freeze',
    concept: 'Heat melts ice. Cold freezes water. Watch what changes!',
    mascotMood: 'happy',
    accentColor: '#134e4a',
  },
  's2-u6': {
    unitId: 's2-u6',
    grade: 2,
    title: 'Unit 6 · Magnets',
    subtitle: 'Metal moves, wood stays',
    concept: 'A magnet pulls metal. It does not pull wood!',
    mascotMood: 'thinking',
    accentColor: '#166534',
  },
  's2-u7': {
    unitId: 's2-u7',
    grade: 2,
    title: 'Unit 7 · Light and Shadow',
    subtitle: 'Block the light',
    concept: 'When something blocks the light, a shadow appears!',
    mascotMood: 'encourage',
    accentColor: '#14532d',
  },
  's2-u8': {
    unitId: 's2-u8',
    grade: 2,
    title: 'Unit 8 · Who Eats What',
    subtitle: 'Grass, rabbit, fox',
    concept: 'A rabbit eats grass, and a fox eats the rabbit!',
    mascotMood: 'celebrate',
    accentColor: '#1e40af',
  },
  's2-u9': {
    unitId: 's2-u9',
    grade: 2,
    title: 'Unit 9 · Soil and Rain',
    subtitle: 'Soak in or wash away',
    concept: 'Soft rain soaks into soil. Hard rain can wash soil away!',
    mascotMood: 'happy',
    accentColor: '#1e3a8a',
  },
  's2-u10': {
    unitId: 's2-u10',
    grade: 2,
    title: 'Unit 10 · Care for Earth',
    subtitle: 'Bin, water, and light',
    concept: 'Rubbish harms a river. Put it in the bin and save water!',
    mascotMood: 'thinking',
    accentColor: '#3730a3',
  },
  's3-u1': {
    unitId: 's3-u1',
    grade: 3,
    title: 'Unit 1 · Leaves Make Food',
    subtitle: 'Light on the leaf',
    concept: 'A leaf uses light to make food. No light, and the leaf turns pale!',
    mascotMood: 'happy',
    accentColor: '#7c2d12',
  },
  's3-u2': {
    unitId: 's3-u2',
    grade: 3,
    title: 'Unit 2 · Body Coverings',
    subtitle: 'Fur, feathers, scales',
    concept: 'Fur and feathers keep animals warm. Scales cover a fish!',
    mascotMood: 'thinking',
    accentColor: '#9a3412',
  },
  's3-u3': {
    unitId: 's3-u3',
    grade: 3,
    title: 'Unit 3 · When a Home Changes',
    subtitle: 'Leave or come back',
    concept: 'A frog leaves a dry pond. It needs a wet home!',
    mascotMood: 'encourage',
    accentColor: '#9f1239',
  },
  's3-u4': {
    unitId: 's3-u4',
    grade: 3,
    title: 'Unit 4 · Air Takes Space',
    subtitle: 'You cannot see it',
    concept: 'Air fills a balloon and takes space. Wind is air on the move!',
    mascotMood: 'celebrate',
    accentColor: '#831843',
  },
  's3-u5': {
    unitId: 's3-u5',
    grade: 3,
    title: 'Unit 5 · Falling and Slowing',
    subtitle: 'Down, then slow',
    concept: 'A ball falls down. A rough slide slows it!',
    mascotMood: 'happy',
    accentColor: '#6b21a8',
  },
  's3-u6': {
    unitId: 's3-u6',
    grade: 3,
    title: 'Unit 6 · Ramps and Levers',
    subtitle: 'Easier push, easier lift',
    concept: 'A ramp helps move a heavy box. A lever can lift a rock!',
    mascotMood: 'thinking',
    accentColor: '#581c87',
  },
  's3-u7': {
    unitId: 's3-u7',
    grade: 3,
    title: 'Unit 7 · Sound Travels',
    subtitle: 'A shake, then a sound',
    concept: 'A shake makes a sound. Far away, that sound is quiet!',
    mascotMood: 'encourage',
    accentColor: '#5b21b6',
  },
  's3-u8': {
    unitId: 's3-u8',
    grade: 3,
    title: 'Unit 8 · A Closed Path',
    subtitle: 'Bulb on, gap off',
    concept: 'A closed path lights a bulb. A gap in the path stops the light!',
    mascotMood: 'celebrate',
    accentColor: '#4c1d95',
  },
  's3-u9': {
    unitId: 's3-u9',
    grade: 3,
    title: 'Unit 9 · Water Goes Around',
    subtitle: 'Up, cloud, rain',
    concept: 'The sun heats water and it rises. Rain falls from a cloud!',
    mascotMood: 'happy',
    accentColor: '#312e81',
  },
  's3-u10': {
    unitId: 's3-u10',
    grade: 3,
    title: 'Unit 10 · Rot Feeds the Soil',
    subtitle: 'Dead leaves become soil',
    concept: 'A dead leaf rots into the soil, and that rot can feed a plant!',
    mascotMood: 'thinking',
    accentColor: '#3b0764',
  },
  's4-u1': {
    unitId: 's4-u1',
    grade: 4,
    title: 'Unit 1 · Roots Drink',
    subtitle: 'Water goes up',
    concept: 'Roots take water up the plant. No water at the roots, and it droops!',
    mascotMood: 'happy',
    accentColor: '#0f172a',
  },
  's4-u2': {
    unitId: 's4-u2',
    grade: 4,
    title: 'Unit 2 · Bones and Muscles',
    subtitle: 'A muscle pulls',
    concept: 'A muscle pulls a bone. One muscle bends the arm. The other makes it straight!',
    mascotMood: 'thinking',
    accentColor: '#7f1d1d',
  },
  's4-u3': {
    unitId: 's4-u3',
    grade: 4,
    title: 'Unit 3 · Sugar Dissolves',
    subtitle: 'Into the water, or not',
    concept: 'Sugar goes into water. Sand stays in the cup!',
    mascotMood: 'encourage',
    accentColor: '#365314',
  },
  's4-u4': {
    unitId: 's4-u4',
    grade: 4,
    title: 'Unit 4 · Light Bounces',
    subtitle: 'A mirror sends it',
    concept: 'A mirror bounces light, so you see a face. A dark cloth stops the light!',
    mascotMood: 'celebrate',
    accentColor: '#155e75',
  },
  's4-u5': {
    unitId: 's4-u5',
    grade: 4,
    title: 'Unit 5 · Poles Push and Pull',
    subtitle: 'Same ends, or not',
    concept: 'Same magnet ends push away. Ends that are not the same pull!',
    mascotMood: 'happy',
    accentColor: '#701a75',
  },
  's4-u6': {
    unitId: 's4-u6',
    grade: 4,
    title: 'Unit 6 · Wheels Help',
    subtitle: 'A heavy box rolls',
    concept: 'A heavy box rolls on wheels. No wheels, and the box stays!',
    mascotMood: 'thinking',
    accentColor: '#44403c',
  },
  's4-u7': {
    unitId: 's4-u7',
    grade: 4,
    title: 'Unit 7 · Float or Sink',
    subtitle: 'Shape, not the lump',
    concept: 'A boat shape floats. A lump of the same thing sinks!',
    mascotMood: 'encourage',
    accentColor: '#1e3a8a',
  },
  's4-u8': {
    unitId: 's4-u8',
    grade: 4,
    title: 'Unit 8 · Cold Makes Drops',
    subtitle: 'On a cold cup',
    concept: 'Drops come on a cold cup. A warm cup stays dry!',
    mascotMood: 'celebrate',
    accentColor: '#1e1b4b',
  },
  's4-u9': {
    unitId: 's4-u9',
    grade: 4,
    title: 'Unit 9 · Longer Days',
    subtitle: 'More sun, it grows',
    concept: 'More sun, and the plant grows. A short day, and the plant rests!',
    mascotMood: 'happy',
    accentColor: '#3f6212',
  },
  's4-u10': {
    unitId: 's4-u10',
    grade: 4,
    title: 'Unit 10 · One Link Breaks',
    subtitle: 'The eater goes too',
    concept: 'No food, and the eater goes. If the rabbits go, the fox goes too!',
    mascotMood: 'thinking',
    accentColor: '#4a044e',
  },
};

export const ALL_UNIT_INTROS: Record<string, UnitIntroDef> = {
  ...GRADE_1_INTROS,
  ...GRADE_2_INTROS,
  ...GRADE_3_INTROS,
  ...GRADE_4_INTROS,
  ...GRADE_5_INTROS,
  ...GRADE_6_INTROS,
  ...READ_INTROS,
  ...SCIENCE_INTROS,
};

export function getUnitIntro(unitId: string): UnitIntroDef | null {
  return ALL_UNIT_INTROS[unitId] ?? null;
}
